steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - europe-west3-docker.pkg.dev/$PROJECT_ID/videoanalyzer-richi-solutions/app:$COMMIT_SHA
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - europe-west3-docker.pkg.dev/$PROJECT_ID/videoanalyzer-richi-solutions/app:$COMMIT_SHA

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - videoanalyzer-richi-solutions
      - --image
      - europe-west3-docker.pkg.dev/$PROJECT_ID/videoanalyzer-richi-solutions/app:$COMMIT_SHA
      - --region
      - europe-west3
      - --platform
      - managed

images:
  - 'europe-west3-docker.pkg.dev/$PROJECT_ID/videoanalyzer-richi-solutions/app:$COMMIT_SHA'
